### ISSUE TITLE
Show Raw respose instead of Json

### ISSUE THREAD

**Issue by Bgichuru** [Krazal/nppopenai#10]
Hi.
Do you mind showing the raw response instead of Json. seems attempting to parse is causing most issues.

Thanks.

**Comment by Krazal** [comment]
Hi!

It's possible, that you're using NppOpenAI v0.1.5 which contains a memory/response handling bug. (You can check it out from the menu: Plugins » NppOpenAI » About.)

This bug has been fixed in v0.2 which is available here:
x64: https://github.com/Krazal/nppopenai/releases/download/v0.2/NppOpenAI_x64.zip
x86: https://github.com/Krazal/nppopenai/releases/download/v0.2/NppOpenAI_x86.zip

You should unzip the appropriate downloaded file to the NppOpenAI plugin folder which is by default:
`c:\Program Files (x86)\Notepad++\plugins\NppOpenAI\`

Additionally, it was a good idea to show the response messages/errors in the main window (instead of a message box), so the next update will contain this feature; also it will include some chat support, too.

**Comment by Bgichuru** [comment]
Works like charm.

Thanks :)
